### ISSUE TITLE
你好，能分享下完成的EFI么？

### ISSUE THREAD

**Issue by qq4555286** [imcort/M910x-hackintosh-EFI#1]
我是新手，我的配置跟你一样，能分享下完整的EFI么？

**Comment by imcort** [comment]
@qq4555286 您好，感谢选择使用我的EFI，请直接下载Release里的压缩包，解压至您的EFI分区中即可使用。请注意需要参考司波图教程，对CFG Lock解锁后才能使用。

**Comment by qq4555286** [comment]
> @qq4555286 您好，感谢选择使用我的EFI，请直接下载Release里的压缩包，解压至您的EFI分区中即可使用。请注意需要参考司波图教程，对CFG Lock解锁后才能使用。

**Comment by qq4555286** [comment]
> @qq4555286 您好，感谢选择使用我的EFI，请直接下载Release里的压缩包，解压至您的EFI分区中即可使用。请注意需要参考司波图教程，对CFG Lock解锁后才能使用。

压缩包只有一个1k的文件，是我没操作对么？

**Comment by imcort** [comment]
已更新Release
